### ISSUE TITLE
httpclient authorization

### ISSUE THREAD

**Issue by danwoolley** [estately/rets#100]
I had an incident today where I hooked HTTPScoop up to my traffic and noticed the following: each search would consist of a POST request with search criteria but no Authorization header, a response with an auth failure ReplyText, another POST request with the same exact search criteria and an Authorization header, a response with the requested data. So each search is actually a pair of requests, one with valid Authorization, one without. A valid search gives a valid result, but it takes twice as many steps as it should.

The log file generated by the gem does not reflect this. It shows one request and response for each search. This fact, combined with looking through the gem code, leads me to believe that the Authorization header is automatically handled at a lower level, in the HTTPClient. You can see this using the bin/rets example script, so I've eliminated my code causing the issue.

I'm wondering if you guys have noticed this, if it's just an artifact of abstracting the request/response cycle to HTTPClient, if there's something setting I don't know about, etc. I'm happy to work on a pull request if I can figure it out, but just wanted to get your opinion first.

**Comment by dougcole** [comment]
I haven't had a chance to verify this, but if you can and have the time to fix it I'd love to merge the pull request!

**Comment by galweiss** [comment]
Any update regarding this issue?

**Comment by danwoolley** [comment]
I dove down into the HTTPClient and could not figure this out myself. My feeling is that HTTPClient abstracts auth away from the developer, so it knows that auth failed and it should re-auth automatically. If we could figure out how to make the auth "stickier" - so that it only had to auth once per session - things would get a lot more efficient for everyone.

**Comment by tdtran** [comment]
@danwoolley this is how http authentication works. The client sends an http request to the server, the requested resource requires authentication / authorization, the server responds with a challenge. The client takes the challenge, inserts the login credentials, then repeats the request. The server checks the credentials and if they pass, it returns the resource. All this client/server dance is handled automatically by HTTPClient.

In the case of basic http authentication, the client can preemptively include its login credentials. Only one round of request/response is needed. It's not entirely correct according to the protocol but it works. I don't know if HTTPClient does it.

Digest HTTP authentication always requires two rounds. In the first round the server responds with a one-time generated challenge. In the second round the client must take that challenge and generates a digest based on the challenge (nonce) and its username / password. That's to prevent replay attacks.

I think what you observed is OK. Not the most efficient but it is how HTTP works.

**Comment by danwoolley** [comment]
Ok - good explanation. It just looks funny in the sniffer, but all that
makes sense now.

**Comment by tdtran** [comment]
It seems we explained the problem and there is nothing to do. I close this issue. If you disagree, feel free to reopen and say why.

Thanks for helping.
