### ISSUE TITLE
Getting "unknown capability Search, available capabilities []" error in NWMLS instead of Rets::AuthorizationFailure

### ISSUE THREAD

**Issue by danwoolley** [estately/rets#102]
Give bogus id/pwd to NWMLS Matrix RETS server and you don't get an auth failure:

[Dan@lilmac2 rets (master*)]$ bin/rets http://rets.matrix.nwmls.com/rets/login.ashx -U bogus -P bogus -m
/Users/Dan/Dev/rets/lib/rets/client.rb:313:in `capability_url': unknown capability GetMetadata, available capabilities [] (Rets::UnknownCapability)
  from /Users/Dan/Dev/rets/lib/rets/client.rb:291:in `retrieve_metadata_type'
  from /Users/Dan/Dev/rets/lib/rets/client.rb:285:in `block in retrieve_metadata'
  from /Users/Dan/Dev/rets/lib/rets/client.rb:284:in `each'
  from /Users/Dan/Dev/rets/lib/rets/client.rb:284:in `retrieve_metadata'
  from /Users/Dan/Dev/rets/lib/rets/client.rb:278:in `metadata'
  from bin/rets:118:in `<main>'

It looks like in Client::ErrorChecker, if the status_code is 401, but the response body is valid XHTML with no RETS element, it just returns nothing. I believe it should ignore valid XHTML if it has no RETS element and continue on, then treat the status_code 401 as an AuthorizationFailure.

I've got a PR I'll submit to fix this.

**Comment by dougcole** [comment]
fixed in #103
