### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by summera** [estately/rets#125]
@dougcole @hfaulds 

Could we start tagging releases of `rets`? That way it's easier to see when a release was made and at what commit :yum:

**Comment by dougcole** [comment]
agreed. https://github.com/jbarnette/hoe-git looks like it'll do what we want as part of the release process. I'll be sure to add that before the next release.

**Comment by dougcole** [comment]
They will be tagged from here on out!

https://github.com/estately/rets/pull/129 and a sample: https://github.com/estately/rets/releases/tag/v0.9.0

**Comment by summera** [comment]
great! :+1:
