### ISSUE TITLE
Rets 0.8.1 not on Rubygems

### ISSUE THREAD

**Issue by summera** [estately/rets#128]
https://rubygems.org/gems/rets/versions

@dougcole could we get this version out pretty please? :)

**Comment by hfaulds** [comment]
I would vote for https://github.com/estately/rets/pull/127 being merged first. We haven't had a chance to start running this in production yet unfortunately.

**Comment by summera** [comment]
@hfaulds `0.8.1` still uses Webagent, not `http-cookie` (https://github.com/estately/rets/commits/master). 

Def agree that we should merge in https://github.com/estately/rets/pull/127 and test in prod before releasing `0.9` though

**Comment by dougcole** [comment]
odd, I see the release code in my bash history and don't remember it failing, but you're right it wasn't there. It is now. :+1:

**Comment by summera** [comment]
thanks mate
