### ISSUE TITLE
Double Authentication

### ISSUE THREAD

**Issue by zoesteinkamp** [estately/rets#146]
I am working with the Rhode island MLS system and they are saying they have double authentication. After I login to the RETS server through your system I can not go any further because I need to login for a second time with a user-agent username and password. Do you have any idea how I might set this up with your system? Or have you dealt with any other double authentication system?

**Comment by hfaulds** [comment]
There are two options to the gem that you'll need to pass in: `:agent` and `:ua_password`

**Comment by zoesteinkamp** [comment]
Will it look like this? 


```ruby
client = Rets::Client.new({
                              login_url: 'http://ris.retsiq.com/rets/login',
                              username: '341',
                              password: 'c99',
                              version: 'RETS/1.5'
                             agent: Blah
                             ua_password : blah

                          })
```

**Comment by hfaulds** [comment]
Yes, that looks good to me. I commented out your username and password for you though.

**Comment by hfaulds** [comment]
@zoesteinkamp feel free to reopen if you still struggle to authenticate with them

**Comment by hfaulds** [comment]
We could definitely do with some better documentation of our options as well.

**Comment by zoesteinkamp** [comment]
I am not struggling with the auth anymore I believe but I am slightly confused still by how I get property data. I am following this document http://www.reso.org/assets/Certifications/resodatadictionarycertificationoverview_v1.0.3_2015_0330.pdf,

With the assumption this is how I should be able to pull out data. Say I have a property, but IDK if its a house or condo, I just have its mLs_id. And I want to know the address(street,city,country, etc..) and if it has an off the market date. How would I do that with your system?
