### ISSUE TITLE
rets_class_name is integer

### ISSUE THREAD

**Issue by Galaxy83** [estately/rets#170]
I got a RETS provider who return rets_class_name as integer so the method 'find_rets_class' cannot find any classes.
Should be fixed to:
rets_classes.detect {|rc| rc.name == rets_class_name.to_s }

Thanks.

**Comment by dougcole** [comment]
I think I'm missing some context, but it seems like you should be able to pass the `rets_class_name` in as a string instead.

If I'm wrong above, could you help explain the scenario where you are having problems? Thanks!

**Comment by Galaxy83** [comment]
I could have sworn I was passing a String. I wasn't. Had [1,2,3] instead of ["1","2","3"] in a Yaml file.
Then I was sure that rets_class_name was passed from the provider.
DOH!

**Comment by dougcole** [comment]
No problem, I'll close this issue then.
