### ISSUE TITLE
Plans for new release

### ISSUE THREAD

**Issue by sivicencio** [estately/rets#172]
Hey guys,

Thanks for this awesome gem. It saved me a lot of work. I have some questions though:

1. Do you have a roadmap or new release dates planning? I've seen you've already made lots of improvements in the master branch.
2. Are there plans to support `STANDARD-XML` format for search? I'm using version `0.9.0`, and when I try to use this format, it returns nil when using the search transaction (`find` method in the gem context).

I also saw you need some help with the Readme. I've been playing a lot with the gem to get the desired results, and I could add info like retrieving lookup types for a `resource` instance, tables for a `rets_class` instance (good for understanding attributes metadata like name and types), or even how to search with more options. If you have content ideas or guidelines for the usage, you tell me and I can write something.

Cheers.

**Comment by dougcole** [comment]
@sivicencio Glad you like the gem!

> Do you have a roadmap or new release dates planning? I've seen you've already made lots of improvements in the master branch.

Internally we bundle gems off of master, so we haven't been particularly good about regular releases, but I'll make sure we make one soon.

> Are there plans to support STANDARD-XML format for search? I'm using version 0.9.0, and when I try to use this format, it returns nil when using the search transaction (find method in the gem context).

This isn't really planned. I've seen the format, but haven't had any need for it. I'm curious about what your interest in it is? I don't expect we'll be adding support for it any time as this is definitely a gem we wrote to scratch our own itch, but if it's something you're interested in I'd be happy to talk to you about it and merge a pull request with the related code.

**Comment by dougcole** [comment]
> I also saw you need some help with the Readme. I've been playing a lot with the gem to get the desired results, and I could add info like retrieving lookup types for a resource instance, tables for a rets_class instance (good for understanding attributes metadata like name and types), or even how to search with more options. If you have content ideas or guidelines for the usage, you tell me and I can write something.

We'd love help with documentation! We don't have any specific guidelines, but if you're interested in helping just add documentation to anything you found confusing! Even just making a list of things you found confusing would be helpful, so we know what to document next.

**Comment by dougcole** [comment]
Sorry for the slow turn around on this, but I've pushed a new version: https://rubygems.org/gems/rets
