### ISSUE TITLE
retscli

### ISSUE THREAD

**Issue by summera** [estately/rets#182]
I've created [retscli](https://github.com/summera/retscli) to ease integration with RETs servers. It is using the rets gem underneath, so I wanted to thank you guys for your work on this 🍻 . Hopefully retscli will be of some use to you!

I'm still making improvements and adding features so any feedback/ideas you all have is greatly appreciated. Would you mind mentioning `retscli` in your README? Hopefully this is helpful to others, working with the rets gem. Looking to make integration as smooth as possible based on everyone's experiences.

Thanks!

**Comment by dougcole** [comment]
This is super cool, thanks @summera! I haven't done a lot of rets work in the past month, so I haven't played with it a ton, but it looks super slick and I'm excited to try it soon!
