### ISSUE TITLE
RESO Web API 1.x

### ISSUE THREAD

**Issue by webavant** [estately/rets#193]
Can anyone in this project share a little knowledge on the state of existing and libraries for the existing and coming APIs as regulated by RESO's upcoming Web API specification? The RESO organization regulates all MLS platforms and mandates this new API spec, due for deadline in several days. I'm really liking this library and I'm feeling reluctant to move to new the RESTful APIs for various reasons. 

Hoping general questions are welcome in this issue queue, but let me know otherwise and I'll delete!

**Comment by dougcole** [comment]
I know very little about the new APIs that are coming. In my experience MLSes don't move that fast with technology, so I'm definitely planning to just wait and see what comes, rather than try and prepare for it now.

That said, a REST API with a sane authentication method would be awesome.
