### ISSUE TITLE
Getting Agent/Office details using unique identifiers

### ISSUE THREAD

**Issue by rajdeepbhatia** [estately/rets#195]
FMLS has stopped returning many fields when we query for a property using MLS Number. Instead, now they return unique identifers of Agent/Office(e.g. ListAgent_MUI, ListOffice_MU, SellingAgent_MUI, SellingOffice_MUI). Currently we only have examples for Property and Photos. Can someone please help how to fetch Agent/Office info now since they have stopped returning ListAgentFullName, SellingAgentFullName, etc with Property fields? Any help would be highly appreciated.

**Comment by mariaheneliko** [comment]
Lmk if you need me to ask FMLS anything specific or if there's anything I can do to help on the business side. -M

**Comment by summera** [comment]
@rajdeepbhatia What metadata tables do they provide for agent and office? My guess is you need to take the unique ID they return for those agent and office resources and query those tables. 

Also just to verify that they aren't sending those fields anymore and it's not something else that's causing the issue, it would be good to look through the property metadata to see if the agent and office info is listed. If it's still listed in the metadata and you aren't seeing it in the returned property data, then I would verify my query and then contact FMLS if it's still an issue.

**Comment by rajdeepbhatia** [comment]
@summera FMLS has notified their users that they won't be providing Agent/Broker names with property because that info could change with time. Instead they are now providing Agent/Broker office unique identifiers instead.

**Comment by dougcole** [comment]
@rajdeepbhatia: Agents and Brokers will work the the same as properties, but with new resource and class names, the exact names are dependent on the mls metadata.
