### ISSUE TITLE
Handling Pagination

### ISSUE THREAD

**Issue by leehumeniuk** [estately/rets#199]
The system I'm connecting to limits the amount of listings returned to 100. I know that there are about 11,000 total.
If the system wants to return more than 100 listings, then the xml comes with a pagination tag that gives the number of pages and the offset, etc.

Is there functionality to loop and request the rest of the pages?

Thanks!

**Comment by dougcole** [comment]
The `#find` method takes a `:offset` and `:limit` keys in the options hash. That should do what you're looking for.

**Comment by gnazarkin** [comment]
Is there a way to get the pagination tag using the client? If not how did you handle it @leehumeniuk? Or did you just make a manual query not using the client and then use the client to get the records? Thanks in advance
