### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by alongoldboim** [estately/rets#202]
Getting: "412 - Precondition set by the client " on current 0.10 version, when switching to current master it doesn't happen, is there an option to do another release.

**Comment by timdorr** [comment]
Looks like this happened: https://rubygems.org/gems/rets/versions/0.11.0

**Comment by dougcole** [comment]
You're right, sorry. I meant to close this issue after it was release!

**Comment by alongoldboim** [comment]
@dougcole thanks!
