### ISSUE TITLE
Which version(s) of the RETS standard does this library work with?

### ISSUE THREAD

**Issue by cmtonkinson** [estately/rets#209]
Would be helpful to have in the README also. I'm in the analysis phase of a project that provides a RETS v2.2 interface and I can't tell whether this library supports that or not.

**Comment by dougcole** [comment]
@cmtonkinson Good question: we support RETS 1.x. We haven't run into any RETS servers in the US that require rets 2.x, so we haven't built support for it.

I can't actually find documentation for RETS 2.2 and wasn't aware that was available. Do you mind linking me to it?

**Comment by cmtonkinson** [comment]
Sorry @dougcole, turns out I was misinformed - it's actually RETS 1.7 I'd be dealing with. Apologies for the confusion, I'm new to realty infosystems so I don't know what I don't know yet.

Given your response - just for my own edification - are 1.x versions of RETS all backwards compatible?

**Comment by dougcole** [comment]
I honestly don't know all the details. You can look at the specifications here: https://www.reso.org/specifications/, but yeah, the differences between the 1.x versions of RETS are much smaller. In practice we've used this gem with Rets 1.5 through 1.8 without problems.

**Comment by perezgildardo** [comment]
version: 'RETS/1.7.2' works fine.

```
client = Rets::Client.new({
  login_url: 'url',
  username: 'username',
  password: 'password',
  version: 'RETS/1.7.2',
  # logger: Logger.new(STDOUT)
})
```
