### ISSUE TITLE
Examples anywhere?

### ISSUE THREAD

**Issue by Siggs2000** [estately/rets#69]
Well, ruby-rets is no longer so I've found this great gem. Thanks for building and maintaining it! 

It's a new world for me here and was just wondering if anyone had any "find" examples. I'm able to create a client and login successfully but every find query I try returns: 

```
Rets::InvalidRequest: Got error code 20203 (Invalid Search Type)
```

or other various syntax errors. 

This is what I'm trying based on what I can gather from the code. 

```
@client.find(:first, {:Bedrooms => 3})
```

Not sure where to enter the search type or property class and I assume that's an issue.

**Comment by piratmc** [comment]
Please provide samples for the query: and class: . What are the values class: can take? 
I do 
`property = client.find(:all, {
    search_type: 'Property',
    class: 'Condo',
    query: '(ID=*)'
})`
and it errors out with 401

**Comment by tyler-king** [comment]
Hey @piratmc I can't remember exactly for sure. The RETS we communicated with was non-standard so the values may differ.

However I believe values were:

+ rental
+ condominium
+ commercial
+ land

**Comment by piratmc** [comment]
@tyler-king thank you. Please take a look again on my question, I updated it with more details and a code I use

**Comment by piratmc** [comment]
It logs in fine (returns agent info etc) but does not like client.find call

**Comment by tyler-king** [comment]
Sadly, I'm not too sure. I'm not the author nor an expert on RETS :) Best I can offer is Class (in my case) needed the values I posted above.

**Comment by Siggs2000** [comment]
@piratmc you have to make a metadata call to each of these RETS sources to see what their class and field names are. Each one is completely different. I've actually worked with CRMLS but I think they may have changed RETS service vendors. 

Last time I used it was over a year ago and this was what a query looked like:
`client.search(:search_type => :Property, :class => :Residential, :status => :Active, :query => "(ListPrice=1000000-100000000)") do |data|`

I think if their RETS vendor has changed, then that query may need to change. Either way, you can find out by making a metadata call first.

**Comment by piratmc** [comment]
@Siggs2000 @tyler-king Thanks a lot! Could you please supply an example of how do I do a metadata call? Also... why do I get 401 (AuthorizationFailure) even tho I did not logout before making a find call?
Appreciate your time!

**Comment by piratmc** [comment]
@Siggs2000 Just tried your snippet and it worked, no errors anymore.

**Comment by Siggs2000** [comment]
@piratmc sweet! I don't have my code handy at the moment, but I believe the metadata call was using this: https://github.com/estately/rets/blob/master/lib/rets/client.rb#L261

**Comment by piratmc** [comment]
Yep, got it, thanks again for your help.

**Comment by piratmc** [comment]
@Siggs2000 Another question: how to add another filtering option to the query:. Lets say I would like to query all listings where ListPrice=100000-1000000 and City=XYZ. What would be the syntax?
Thanks!

**Comment by perezgildardo** [comment]
```
property = client.find (:all), {
  search_type: 'Property',
  class: 'Residential',
  query: '(ListPrice=100000-1000000),(City=XYZ)'
}
```
