### ISSUE TITLE
Retry behavior and 20403 response

### ISSUE THREAD

**Issue by alexfarrill** [estately/rets#79]
It doesn't seem correct that when receiving a reply code "20403" -- "No Object Found" that the request should be retried two more times.  Would it be safe to skip retrying in this case?

**Comment by dougcole** [comment]
OK, this is a new option added in #84, for now it defaults to still raising an error for backwards compatibility, but that will likely be changed in future releases, for now just set the option `:no_records_not_an_error => true` when you call find.
