### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by psugihara** [estately/rets#86]
Looks like nokogiri needs to be updated:

```
Bundler could not find compatible versions for gem "nokogiri":
  In Gemfile:
    rets (>= 0) ruby depends on
      nokogiri (~> 1.5.2) ruby

    rails (= 4.2.0) ruby depends on
      actionmailer (= 4.2.0) ruby depends on
        rails-dom-testing (>= 1.0.5, ~> 1.0) ruby depends on
          nokogiri (1.6.0)
```

I tried here but `bundle update` doesn't seem to change the nokogiri version. I'm unfamiliar with hoe, so I'd appreciate if anyone could point me in the right direction: https://github.com/openlistings/rets/commit/0985c054d178486cbc329ec64bb4a7b65e633af0

**Comment by jDeppen** [comment]
Just ran into this issue on a new project. Here's a fix until the new version is shipped.
```
gem 'rets', :git => 'https://github.com/estately/rets.git'
```
