### ISSUE TITLE
Nokogiri version and Ruby 2.1 in Windows

### ISSUE THREAD

**Issue by eidast** [estately/rets#96]
Recently I update my version of ruby in windows

When I try to load the gem I discover the version nokogiri is quite old.

The problem is this gem dont have the DLL precompiled for ruby 2.1

```
irb(main):001:0> require 'rets'
LoadError: cannot load such file -- nokogiri/2.1/nokogiri
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nokogiri-1.5.11-x86-mingw32/lib/nokogiri/nokogiri.rb:1:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/nokogiri-1.5.11-x86-mingw32/lib/nokogiri.rb:28:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rets-0.6.0/lib/rets.rb:3:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from (irb):1
        from C:/RailsInstaller/Ruby2.1.0/bin/irb:11:in `<main>'
```

I think if the version for nokogiri is change to one more new the problem could be solved.

Im going to play with this a little ... to try to find out a solution.

**Comment by jDeppen** [comment]
Not sure if this will help you but I ran into a similar issue involving nokogiri: [https://github.com/estately/rets/issues/86#issuecomment-70606375](https://github.com/estately/rets/issues/86#issuecomment-70606375)

**Comment by eidast** [comment]
I do that, in running the last version available on github for rets gem, basicly the issue is the last version for nokogiri 1.5 branch (1.5.11) for Windows not have 2.1 ruby dll precompiled, because is quite old.

I think if the rets gem update the nokogiri version the problem could be solved, but i dont know if could cause other problems.

**Comment by dougcole** [comment]
I just pushed version 0.7.0 of the rets gem which relaxes the constraints on which version of nokogiri it depends on, which should fix this problem.

I'll close this issue, but please feel free to re-open if you are still having problems after upgrading to the new version.

**Comment by eidast** [comment]
I check, I proceed to update the gem and the issue was solved.

Solution certified ;)
