### ISSUE TITLE
Undefined method with httpclient 2.6 and http-cookie

### ISSUE THREAD

**Issue by trans1t** [estately/rets#99]
Ran into a snag running `find` with httpclient 2.6 and http-cookie in the Gemfile:

```
NoMethodError: undefined method `match?' for #<WebAgent::Cookie:0x0000010a0b1de0>
	from [path]/lib/rets/http_client.rb:86:in `block in http_cookie'
	from [path]/lib/rets/http_client.rb:85:in `each'
	from [path]/lib/rets/http_client.rb:85:in `http_cookie'
	from [path]/lib/rets/http_client.rb:76:in `rets_extra_headers'
	from [path]/lib/rets/http_client.rb:26:in `http_post'
	from [path]/lib/rets/client.rb:346:in `http_post'
	from [path]/lib/rets/client.rb:146:in `find_every'
	from [path]/lib/rets/client.rb:119:in `find_with_given_retry'
	from [path]/lib/rets/client.rb:114:in `find_with_retries'
	from [path]/lib/rets/client.rb:103:in `find'
```

The httpclient 2.6 CHANGELOG (https://github.com/nahi/httpclient/blob/master/CHANGELOG.md) indicates it will use http-cookie if it exists, so assume that's what's happening (and it did in my case, thanks to the `mechanize` gem).  Also received a number of debug log messages: `Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.`

If I specify httpclient 2.5.3 in the Gemfile, all is well, just figured I should bring it up.

Thanks for everyone's hard work on this excellent gem.

**Comment by dougcole** [comment]
Interesting, thanks for the bug report @trans1t. I've never tested with the `http-cookie` gem so I'm guessing your assumption is correct. I'll take a look at this at some point.

**Comment by summera** [comment]
Also ran into this issue. Will look into submitting a PR to fix

**Comment by dougcole** [comment]
Thanks @summera! I know @hfaulds has looked into this somewhat too, pinging him here so he can chime in.

**Comment by summera** [comment]
@dougcole Check https://github.com/estately/rets/pull/109

I'll put in another PR that makes rets compatible with httpclient 2.6
